### ISSUE TITLE
error in url

### ISSUE THREAD

**Issue by zhangjinzhi** [lyy8510a/OpenMangosteen#2]
访问10103端口失败，访问http://127.0.0.1:10102/account/login也失败。
麻烦author解答下，谢谢。

**Comment by lyy8510a** [comment]
数据库导入了吗，报什么错呢

https://github.com/lyy8510a/OpenMangosteen/blob/master/config/config.py
这里需要配置你的mysql噢

**Comment by zhangjinzhi** [comment]
配置了mysql，正常启动服务器，没有报错
![image](https://user-images.githubusercontent.com/25034635/51176368-b4c04900-18f7-11e9-9fdc-e283f8e72834.png)
但是访问http://127.0.0.1:10103/，会跳转到http://127.0.0.1:10102/account/login?cburl=http://127.0.0.1:10103/
![image](https://user-images.githubusercontent.com/25034635/51176433-d8838f00-18f7-11e9-989c-fb4fd44dd43c.png)
跳转之后，1显示27.0.0.1 拒绝了连接请求。

**Comment by lyy8510a** [comment]
可能是之前代码污染了。。我重传了一次
